version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    depends_on:
      - mongo