name: Build And Push Docker Image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our Code
        uses: actions/checkout@v2

      - name: Get and setup Java JDK 11 with adopt
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build New Jar file
        run: mvn clean install

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nilecity-appen:${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/nilecity-appen:latest

      - name: Upload Jar File
        uses: actions/upload-artifact@v2
        with:
          name: cars-app.jar
          path: target/*.jar
